# Generated by Django 4.0 on 2022-01-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_image_tag_alter_post_options_notification_thread_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
